### PR TITLE
Added a command-line option to set the root path

### PR DESCRIPTION
**Pull request by MathyV**
This allows you to separate your own implementation of plugins and
config from the original repository

### CODE REVIEW

**Comment by llimllib** [comment]
What's your use case for this? Why do you want to keep slask separate from the plugins and config?

**Comment by MathyV** [comment]
I don't want to 'pollute' the slask repo or my own fork of it by adding my own implementation to it. This way I can develop my own Slack bot in a separate directory independent of the slask repo.

Also, it opens the door to installing Slask as a system library (or in a virtualenv using pip) while you can still develop your own version of a bot.

As an example I started my own repo here:
https://github.com/MathyV/slackcraft
I can check them both out next to each other and (after configuration) start the bot with python slask/slask.py -p slackcraft.

Ideally I'd love to have Slask in pip and just start it with slask -p slackcraft but then you need to create a pip package of it.

**Comment by llimllib** [comment]
That's interesting! I'm going to think on it a bit. Thank you so much for the PR and explanation of how you're using it.

**Comment by MathyV** [comment]
I'm sorry, apparently I created this pull request from my master which I shouldn't have, there's a separate branch you can use in my repo.

**Comment by llimllib** [comment]
I've taken a slightly different path, but this is coming shortly! I've reimplimented slask as a binary that you will be able to install with pip. It's in the unfortunately named `add-sqlite` branch if you want to take a look. Should land this week.

**Comment by MathyV** [comment]
That is great! I'll close this pull request so you don't get bothered by my commits anymore :-)

**Pull request closed without merging**
